FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY services/wallet-service/src/ ./

RUN dotnet restore Wallet.API/Wallet.API.csproj
RUN dotnet publish Wallet.API/Wallet.API.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "Wallet.API.dll"]